# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci
# sequence whose values do not exceed four million, find the sum of the even-valued terms.

firstFibNum = 1
secondFibNum = 2
newFibNum = 0
sumOfEvenFib = 0

while (secondFibNum < 4000000):

    if (secondFibNum % 2 == 0):
        sumOfEvenFib += secondFibNum

    newFibNum = secondFibNum
    secondFibNum = firstFibNum + secondFibNum
    firstFibNum = newFibNum

print( "The sum of the even-valued terms fibonacci numbers: " , sumOfEvenFib)